[package]
name = "azure-speech"
version = "0.0.1-alpha"
authors = ["Jure Bernava Prah <webjure@gmail.com>"]
description = "Pure Rust implementation for Microsoft Speech Service."
edition = "2021"
rust-version = "1.71.0"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/jbernavaprah/azure-speech"
homepage = "https://ferrilab.github.io/ferrilab"
include = [
    "Cargo.toml",
    "readme.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "src/*.rs",
    "doc/*.md",
]
categories = ["multimedia", "multimedia::audio", "text-processing"]
keywords = [
    "azure-speech",
    "sdk",
    "cognitive",
    "recognition",
    "synthesizing"
]

[dependencies]
tokio = { version = "1.36.0", features = ["rt-multi-thread", "sync", "fs"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
futures-util = "0.3.30"
url = { version = "2", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
os_info = "3"
log = "0.4.21"
hound = "3.5"



[dev-dependencies]
tokio = { version = "1.36.0", features = ["full"] }
simplelog = "0.12.2"
clap = { version = "4.5.3", features = ["derive"] }
cpal = "0.15.3"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
reqwest = { version = "0.12", features = ["blocking", "stream"] }
iobuffer = "0.2.0"
futures = "0.3.30"
tokio-util = "0.7.10"
