[package]
name = "azure-speech"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "sync", "fs"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
futures-util = "0.3.30"
const_format = { version = "0.2.32" }
url = { version = "2", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde = { version = "1.0.197", features = ["derive"] }
chrono= "0.4.35"
os_info = "3"
log = "0.4.21"
funty = "2.0.0"
hound = "3.5"
cpal = "0.15.3"

[dev-dependencies]
tokio = { version = "1.36.0", features = ["full"] }
simplelog = "0.12.2"
clap = { version = "4.5.3", features = ["derive"] }
anyhow = "1.0.81"
ringbuf = "0.3"
samplerate = "0.2.4"
dasp = { version = "0", features = ["all"] }
fon = {version = "0.6.0"}